let prefix = "../../images/ingredients/" 
let postfix = ".png";

export const imagePath = {
    강황: require(prefix+ "ginger" + postfix),
    건과일: require(prefix+ "dried-fruits" + postfix),
    건어물: require(prefix+ "dried-fish" + postfix),
    게: require(prefix+ "crab" + postfix),
    겨자: require(prefix+ "mustard" + postfix),
    파스타면: require(prefix+ "pasta-noodle" + postfix),
    간장: require(prefix + 'soy-sauce' + postfix),
    감자 : require(prefix + 'potato' + postfix),
    게맛살 : require(prefix + 'crab' + postfix),
    계란 : require(prefix + 'egg' + postfix),
    고추장: require(prefix + "gochujang" + postfix),
    고추참치 : require(prefix + 'salmon' + postfix),
    고춧가루 : require(prefix + 'chili-powder' + postfix),
    골뱅이 : require(prefix + 'whelk' + postfix),
    굴소스 : require(prefix + 'oyster-sauce' + postfix),
    김치 : require(prefix + 'kimchi' + postfix),
    깻잎 : require(prefix + 'perilla' + postfix),
    냉동만두 : require(prefix + 'dumpling' + postfix),
    냉동새우 : require(prefix + 'shrimp' + postfix),
    냉동해물 : require(prefix + 'seafood' + postfix),
    냉면육수 : require(prefix + 'stock' + postfix),
    너구리라면 : require(prefix + 'ramen' + postfix),
    닭가슴살 : require(prefix + 'chicken-breast' + postfix),
    닭다리살 : require(prefix + 'chicken-leg' + postfix),
    닭발 : require(prefix + 'chicken' + postfix),
    닭정육 : require(prefix + 'chicken' + postfix),
    당근 : require(prefix + 'carrot' + postfix),
    당면 : require(prefix + 'noodle' + postfix),
    대파 : require(prefix + 'green-onion' + postfix),
    대패삼겹살 : require(prefix + 'pork' + postfix),
    돈가스_소스 : require(prefix + 'sauce' + postfix),
    돈가스소스 : require(prefix + 'sauce' + postfix),
    돈까스소스 : require(prefix + 'sauce' + postfix),
    돼지고기 : require(prefix + 'pork' + postfix),
    돼지고기_앞다리살 : require(prefix + 'pork' + postfix),
    된장 : require(prefix + 'miso' + postfix),
    두부 : require(prefix + 'tofu' + postfix),
    땅콩버터 : require(prefix + 'peanut-butter' + postfix),
    떡 : require(prefix + 'rice-cake' + postfix),
    라면 : require(prefix + 'ramen' + postfix),
    라이스페이퍼 : require(prefix + 'rice-paper' + postfix),
    마늘: require(prefix+ "garlic" + postfix),
    마라소스 : require(prefix + 'sauce' + postfix),
    마요네즈 : require(prefix + 'mayonnaise' + postfix),
    매운_라면 : require(prefix + 'ramen' + postfix),
    매운라면 : require(prefix + 'ramen' + postfix),
    면사리 : require(prefix + 'noodle' + postfix),
    멸치액젓 : require(prefix + 'sauce' + postfix),
    모짜렐라치즈 : require(prefix + 'mozzarella-cheese' + postfix),
    물 : require(prefix + 'water' + postfix),
    배추 : require(prefix + 'napa-cabbage' + postfix),
    버터 : require(prefix + 'butter' + postfix),
    부추 : require(prefix + 'chives' + postfix),
    부침가루 : require(prefix + 'powder' + postfix),
    불닭볶음면 : require(prefix + 'ramen' + postfix),
    사골곰탕육수 : require(prefix + 'stock' + postfix),
    사리곰탕 : require(prefix + 'ramen' + postfix),
    사리곰탕라면 : require(prefix + 'ramen' + postfix),
    삼겹살 : require(prefix + 'pork' + postfix),
    새우 : require(prefix + 'shrimp' + postfix),
    새우깡 : require(prefix + 'snack' + postfix),
    샐러드_야채 : require(prefix + 'vegetable' + postfix),
    생크림 : require(prefix + 'whipping-cream' + postfix),
    설탕 : require(prefix + 'sugar' + postfix),
    소금 : require(prefix + 'salt' + postfix),
    소면 : require(prefix + 'noodle' + postfix),
    소시지 : require(prefix + 'sausage' + postfix),
    소시지_햄 : require(prefix + 'sausage' + postfix),
    숙주 : require(prefix + 'bean-sprout' + postfix),
    순두부 : require(prefix + 'tofu' + postfix),
    스리라차소스 : require(prefix + 'sauce' + postfix),
    슬라이스치즈 : require(prefix + 'cheese' + postfix),
    시판용육개장 : require(prefix + 'stock' + postfix),
    식초 : require(prefix + 'vinegar' + postfix),
    쌀국수 : require(prefix + 'noodle' + postfix),
    쌀국수면 : require(prefix + 'noodle' + postfix),
    쌈장 : require(prefix + 'miso' + postfix),
    안주닭발 : require(prefix + 'chicken' + postfix),
    애호박 : require(prefix + 'squash' + postfix),
    야채 : require(prefix + 'vegetable' + postfix),
    양배추 : require(prefix + 'cabbage' + postfix),
    양파 : require(prefix + 'onion' + postfix),
    어묵 : require(prefix + 'fish-cake' + postfix),
    연겨자 : require(prefix + 'mustard' + postfix),
    오이 : require(prefix + 'cucumber' + postfix),
    오징어땅콩 : require(prefix + 'snack' + postfix),
    옥수수: require(prefix+ "corn" + postfix),
    옥수수캔 : require(prefix + 'corn-can' + postfix),
    올리브유 : require(prefix + 'olive-oil' + postfix),
    우동면 : require(prefix + 'noodle' + postfix),
    우동면사리 : require(prefix + 'noodle' + postfix),
    우동사리 : require(prefix + 'noodle' + postfix),
    우유 : require(prefix + 'milk' + postfix),
    진간장 : require(prefix + 'soy-sauce' + postfix),
    진라면 : require(prefix + 'ramen' + postfix),
    진순이 : require(prefix + 'ramen' + postfix),
    짜장라면 : require(prefix + 'ramen' + postfix),
    쫄면 : require(prefix + 'noodle' + postfix),
    쫄면_사리 : require(prefix + 'noodle' + postfix),
    쫄면사리 : require(prefix + 'noodle' + postfix),
    차돌박이 : require(prefix + 'beef' + postfix),
    참기름 : require(prefix + 'sesame-oil' + postfix),
    참치 : require(prefix + 'salmon' + postfix),
    참치캔 : require(prefix + 'tuna-can' + postfix),
    청경채 : require(prefix + 'bok-choy' + postfix),
    청양고추 : require(prefix + 'chili-pepper' + postfix),
    치즈 : require(prefix + 'cheese' + postfix),
    치킨 : require(prefix + 'chicken' + postfix),
    카레가루 : require(prefix + 'curry-powder' + postfix),
    콩나물 : require(prefix + 'bean-sprout' + postfix),
    토마토_소스 : require(prefix + 'sauce' + postfix),
    토마토소스 : require(prefix + 'sauce' + postfix),
    토마토스파게티소스 : require(prefix + 'sauce' + postfix),
    통깨 : require(prefix + 'sesame' + postfix),
    틈새라면 : require(prefix + 'ramen' + postfix),
    파스타_면 : require(prefix + 'noodle' + postfix),
    파스타면 : require(prefix + 'noodle' + postfix),
    파프리카 : require(prefix + 'paprika' + postfix),
    팽이버섯 : require(prefix + 'mushroom' + postfix),
    표고버섯 : require(prefix + 'mushroom' + postfix),
    홍고추 : require(prefix + 'chili-pepper' + postfix),
    후추 : require(prefix + 'pepper' + postfix),
    훈제오리 : require(prefix + 'duck' + postfix),
}
